[tool.poetry]
name = "poetry-bundle-plugin"
version = "0.1.0"
description = "Poetry plugin to bundle projects into various formats"
authors = ["Sébastien Eustace <sebastien@eustace.io>"]
license = "MIT"
readme = "README.md"

packages = [
    { include = "poetry_bundle_plugin", from = "src" }
]

include = [
    { path = "tests", format = "sdist" }
]

[tool.poetry.dependencies]
python = "^3.6"
poetry = "^1.2.0a2"

[tool.poetry.dev-dependencies]
black = { version = "^21.4b1", python = "^3.6.2"}
isort = "^5.8.0"
pre-commit = { version = "^2.6", python = "^3.6.1" }
pytest = "^6.2.3"
pytest-mock = "^3.6.1"

[tool.poetry.plugins."poetry.application.plugin"]
export = "poetry_bundle_plugin.plugin:BundleApplicationPlugin"

[tool.black]
target-version = ['py37']
preview = true

[tool.isort]
py_version = 37
profile = "black"
force_single_line = true
combine_as_imports = true
lines_between_types = 1
lines_after_imports = 2

[tool.mypy]
check_untyped_defs = true
ignore_missing_imports = true
show_error_codes = true
warn_redundant_casts = true
warn_unused_configs = true
warn_unused_ignores = true
files = "src"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
